### ISSUE TITLE
ModuleNotFoundError during initializing

### ISSUE THREAD

**Issue by Jellybeanz1980** [JonasPed/homeassistant-eloverblik#103]
Hello,

All of a sudden Eloverblik sensor can't be initialized anymore. During the Homeassistant starting up an error message saying "ModuleNotFoundError: No module named 'custom_components.eloverblik.s'". The integration has been deleted, and reinstalled using HACS with the same result. Do you guys any idea , what's wrong here?

**Comment by JonasPed** [comment]
Have you done any other changes like upgrading HA?

**Comment by Jellybeanz1980** [comment]
Yes, I upgraded HA, but as far as I remember Eloverblik was OK until I restarted the HA.

**Comment by JonasPed** [comment]
Sure you did not try to implement the suggested change in https://github.com/JonasPed/homeassistant-eloverblik/pull/104/commits/413ee921bedadb056f9b3387dc34ca3cce9df863? I was testing that PR yesterday and it was the only way I was able to reproduce the error.

**Comment by Jellybeanz1980** [comment]
The issue seems to be solved with the new version. Thank you for your effort.

**Comment by JonasPed** [comment]
Great. Closing the issue.
