### ISSUE TITLE
Feature request - support for solarpower

### ISSUE THREAD

**Issue by martinheidemann** [JonasPed/homeassistant-eloverblik#13]
First of all great addon to Home Assistant.

In my data from eloverblik.dk i can see data from my solar cells.
I have attached raw data and a screenshot where you can see what the different "målepunkt id" are.

If possible if would like sensors for all id's:
"Leveret til net"
"Forbrugt fra net"
"Nettoforbrug"
![overblik over målepunkter](https://user-images.githubusercontent.com/59659603/80788087-78fed080-8b88-11ea-9c6d-961ae00935df.PNG)

[Meterdata .xlsx](https://github.com/JonasPed/homeassistant-eloverblik/files/4562775/Meterdata.xlsx)

**Comment by JonasPed** [comment]
I will be happy to add that. Only problem is that I don't have any solar panels, so I am not able to test it. Unfortunately the attached data is not to much use as the eloverblik API delivers an JSON structure. 

What happens if you add one of the other metering points?

**Comment by martinheidemann** [comment]
Hi Jonas
That is a very good idea. I had not thought of adding the integration for every sensor.
I can confirm that this approach works.

I just added the extra sensor for solar power and now i get both values.
The extra sensors will just get the extension "_2" compared to the first sensors.

![multiple sensors](https://user-images.githubusercontent.com/59659603/81052648-1da04b80-8ec4-11ea-8cd5-cce1e1c21b48.png)

**Comment by JonasPed** [comment]
Closing as integration just needs to be added multiple times.
