### ISSUE TITLE
 [custom_components.eloverblik] Exception: <class 'requests.exceptions.ReadTimeout'>

### ISSUE THREAD

**Issue by dekiesel** [JonasPed/homeassistant-eloverblik#16]
Hej,

I got this error after installing the component and setting a meterpoint and token:

```
2020-10-14 09:42:43 DEBUG (SyncWorker_7) [pyeloverblik.eloverblik] Got short lived token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlblR5cGUiOiJDdXN0b21lckFQSV9EYXRhQWNjZXNzIiwidG9rZW5pZCI6IjY
xODNjOWYzLWVkMWUtNDE4ZS04NzEyLTU4ZmQzMTg5MzgxYSIsImp0aSI6IjYxODNjOWYzLWVkMWUtNDE4ZS04NzEyLTU4ZmQzMTg5MzgxYSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVud
GlmaWVyIjoiUElEOjkyMDgtMjAwMi0yLTIzODg4NzI0MDEyMSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2dpdmVubmFtZSI6IkRhdmlkIFN0ZYBoYW4gUnVkb2xmIEtlc3NlbGhlaW0iLCJsb2dpblR
5cGUiOiJLZXlDYXJkIiwicGlkIjoiOTIwOC0yMDAyLTItMjM4ODg3MjQwMTIxIiwidHlwIjoiUE9DRVMiLCJleHAiOjE2MDI3NDc3NjMsImlzcyI6IkVuZXJnaW5ldCIsInRva2VuTmFtZSI6ImhhIiwiYXVkIjoiRW5lcmdpbmV0In0.lJkz4s1JPt5TWJY6I
r3-FiQa0DI3pxb3rCo5aU_SOJo
2020-10-14 09:42:48 WARNING (SyncWorker_7) [custom_components.eloverblik] Exception: <class 'requests.exceptions.ReadTimeout'>
```
I changed the short lived token slightly, don't know if that was necessary.

Any way I can debug this further?

**Comment by dekiesel** [comment]
It started working by itself, no idea what changed. Network hiccup maybe?

I guess this can be closed.

**Comment by dekiesel** [comment]
I just noticed that the 25 generated sensor show data for the day before yesterday, is that normal?

Today is the 14th, the data shown is for the 12th. I thought the sensor were for the last 24 hours (so the 13th)?

**Comment by HBDK** [comment]
it is normal, in fact two days seems rather good i'm currently getting data from the 10th.

**Comment by JonasPed** [comment]
The error you get is due to an timeout from eloverblik.dk api. There is not much I can do about that. 

Regarding the the age of data i just read the latest data available on eloverblik.dk.
