### ISSUE TITLE
HOW-TO: postgresql query to show graph by metering date

### ISSUE THREAD

**Issue by dekiesel** [JonasPed/homeassistant-eloverblik#17]
I hope it is ok I share this here, if not please just delete it.

For everybody else who uses timescaledb as a backend for grafana I thought I'd like to share the query I come up with to show total energy usage by actual metering date.

```
select avg(state),
      time
from(
		select cast(state as decimal)
				,to_date(replace(cast(json_extract_path(attributes::json,'metering_date') as text),'"',''),'YYYY-MM-DD') as time
		from public.ltss
		where entity_id = 'sensor.eloverblik_energy_total'
		and $__timeFilter("time") 
) as a
group by time
```

The problem with just using `time` was twofold: The data shown was actually for another date and if you just used aggregate you'd aggregate over date boundaries. 

This shows the data by metering date and correctly averages without crossing date boundaries.

**Comment by dekiesel** [comment]
The drawback with this method is that you always need to unpack `attributes` for every row and I am afraid this might make my dashboard sluggish in the feature so I wanted to put the hourly sensors into their own table so I could use an index when computing daily,weekly,monthly,yearly averages.

Create a new table:

```
CREATE TABLE eloverblik(
   sensor varchar(100),    
   metering_date date,  
   value numeric,
   insource_date timestamp without time zone,	
   PRIMARY KEY (metering_date, sensor)
);
```
Optional: Add the values you have saved so far:
```

with CTE as ( 
	select *
	,row_number() over (partition by entity_id, state, metering_date order by time desc) as rn
	from (
			select time,
					entity_id,
				   cast(state as decimal)
					,to_date(replace(cast(json_extract_path(attributes::json,'metering_date') as text),'"',''),'YYYY-MM-DD') as metering_date
					
			from public.ltss
			where entity_id like 'sensor.eloverblik_%'

	) a
)

insert into eloverblik
select entity_id as sensor,
		metering_date,
		state as value,
		time as insource_date

from cte where rn = 1 and entity_id != 'sensor.eloverblik_energy_total'
```

I am excluding`total` because I don't want to mix the types of sensors (hourly/total) and because I can compute the daily total from the hourly sensors.

To automatically update `eloverblik` create this function and trigger:

```
CREATE OR REPLACE FUNCTION eloverblik_insert()
  RETURNS TRIGGER 
  LANGUAGE PLPGSQL
  AS
$$
BEGIN
	if NEW.entity_id like 'sensor.eloverblik_energy_%' 
	and NEW.entity_id <> 'sensor.eloverblik_energy_total'
	THEN
		 INSERT INTO eloverblik(sensor, metering_date, value, insource_date)
		 VALUES(NEW.entity_id,to_date(replace(cast(json_extract_path(NEW.attributes::json,'metering_date') as text),'"',''),'YYYY-MM-DD'),cast(NEW.state as decimal),now())
		ON CONFLICT (metering_date,sensor) DO UPDATE SET   (value, insource_date) = (cast(NEW.state as decimal),now());
	END IF;

	RETURN NEW;
END;
$$

CREATE TRIGGER eloverblik_insert
  AFTER INSERT
  ON ltss
  FOR EACH ROW
  EXECUTE PROCEDURE eloverblik_insert();
```

Let me know if you'd rather have this in the wiki.

**Comment by JonasPed** [comment]
it should not be in the issue tracker. You are welcome to create a PR to include the information in some documentation.

**Comment by JonasPed** [comment]
Closing the issue as no PR have been received and this really do not belong in the issue tracker.
