### ISSUE TITLE
Error 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by Nordicfastware** [JonasPed/homeassistant-eloverblik#2]
Goes through great with config_flow but i get an error for all sensors  XX_YY:

` 2020-02-03 18:32:19 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.eloverblik_energy_14_15 fails                                    
Traceback (most recent call last):
[...]
 File "/usr/local/lib/python3.7/site-packages/pyeloverblik/models.py", line 53, in get_metering_data                                                    
    return self._metering_data[hour-1]                                                                                                                   
TypeError: 'NoneType' object is not subscriptable`

**Comment by JonasPed** [comment]
Should be solved now.
