### ISSUE TITLE
not showing up in configuration--integrations

### ISSUE THREAD

**Issue by SinnoTech** [JonasPed/homeassistant-eloverblik#20]
Installed via HACS, after restart, the integration cannot be found to follow these steps:

Head to configuration --> integration
Add new and search for eloverblik
enter refresh token and metering point.

**Comment by LK-lkbackline** [comment]
i have same problem... did you find a fix?

**Comment by SinnoTech** [comment]
> i have same problem... did you find a fix?

Honestly I cannot remember. It is working now. I think it was a restart. Sorry i cant be of more help.

**Comment by LK-lkbackline** [comment]
Reset browser🤗

søn. 10. jan. 2021 12.10 skrev SinnoTech <notifications@github.com>:
