### ISSUE TITLE
Not showing up in integrations

### ISSUE THREAD

**Issue by Varming73** [JonasPed/homeassistant-eloverblik#21]
I've installed using HACS and restarted but can't find eloverblik in Configuration >> Integrations.

I've checked the custom components folder and eloverblik is present in there. I'm using Home Assistant 2021.2.3

**Comment by JonasPed** [comment]
Have you tried to restart your entire HA instance and clear your browser cache?

**Comment by sorenraaschou** [comment]
I have a similar problem - also after trying what you recommend above

**Comment by Waseh** [comment]
I've also experienced this but i can't seem to reliably reproduce it

**Comment by larsbloch** [comment]
I have the same problem. Can the settings be setup manually in a config. Maybe you could put an example in the github readme ?

**Comment by JonasPed** [comment]
I just did a clean install of Home Assistant, added HACS and then Eloverblik integration. Restartet Home Assistant as required. Did not have any issue setting up the integration. 

Any errors in the logs?

**Comment by Rocologo** [comment]
I have the same problem. I have restarted and cleared the cache but but Im not afsked for the målepunkt and the key for eloverblik.. also i dont see it in the log??.

**Comment by Rocologo** [comment]
Maybe you could add a "Configure" button which askes for the Metering point and the token?

**Comment by Rocologo** [comment]
I found this guide: https://robotnet.dk/2020/eloverblik-i-home-assistant.html

Which made me realize what the problem was. I had not understod that I had to add the Integration twice. First in HACS, secondly in normal Home Assistant Integration. After i added the second step, my problems was solved.

I suggest that you make this more clear in to Readme.md file so you get less support.

**Comment by JonasPed** [comment]
Actually that is not different compared to any other integration installed through HACS. I have however updated the README.md file to clarify it.
