### ISSUE TITLE
Not a bug - Just to let you know I reused your code.

### ISSUE THREAD

**Issue by kpoppel** [JonasPed/homeassistant-eloverblik#22]
Hi Jonas

 I just wanted to tell you that I reused your code to create two more HA plugins: Novafos (via KMD data warehouse) and one for regional heating (aka fjernvarme) for use with the eforsyning data warehouse.
 Like the electricity data, everything is non-real-time and 24 hours delayed.  Real-time monitoring requires hardware in your own house it seems.

 Status for these is "works for me", and I also haven't figured out how to publish them on HACS.  I am kind of hoping you can help me out here as the plugins are basically the same as this one, just accessing a different REST API.

Check it out here:
* https://github.com/kpoppel/homeassistant-eforsyning
* https://github.com/kpoppel/homeassistant-novafos

**Comment by pesor** [comment]
Actually, you can read the Kamstrup meter directly. I do that every day, and have an Update every 10 seconds. 

See my repository: https://github.com/pesor/Kamstrup-Omnipower.

**Comment by kpoppel** [comment]
That is pretty clever.  I made the other plugins for those which are reluctant to put together electronics and embedded software.  The 24h delay is okay for many I think... unless there is a leaky pipe, then it is hard to know the same day through HA at least :-)

I will definitely look into the Kamstrup code, thanks for the tip.
