### ISSUE TITLE
Max age is only 10 days

### ISSUE THREAD

**Issue by Realpsudo** [JonasPed/homeassistant-eloverblik#25]
I have a the following added to my configuration:
`- platform: statistics
    entity_id: sensor.eloverblik_energy_total
    name: Eloverblik Monthly Statistics
    sampling_size: 50
    max_age:
        days: 30

But the Min age in the stats overview only shows a dates up till 10 days ago.
`Sampling size
50
Count
18
Mean
29.22
Median
27.45
Standard deviation
8.09
Variance
65.49
Total
525.88
Min value
16.37
Max value
41.95
**Min age
2021-03-17T02:13:21.070741+00:00
Max age
2021-03-27T02:18:34.059234+00:00**
Change
-11.74
Average change
-0.69
Change rate
0

Is there a fix for that?

**Comment by JonasPed** [comment]
Sounds like your recorder is not configured to hold more than 10 days of history.

**Comment by Realpsudo** [comment]
Hej Jonas 
Hvordan/hvor ændre jeg det?
Tak for svar :)

**Comment by JonasPed** [comment]
It is configured in the recorder component.
