### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by cokeman0** [JonasPed/homeassistant-eloverblik#28]
please add sensors, that pull monthly stats.
e.g

sidste_aar_jan
sidste_aar_feb
....
dette_aar_jan
dette_aar_feb
---

**Comment by drhousedk2** [comment]
I vote for this. I really need to be able to fetch this. The data is available with Eloverblik :-)

**Comment by usma0118** [comment]
+1

**Comment by runemoennike** [comment]
I've made a PR to the underlying pyeloverblik package which should make this feature pretty easy to implement.
