### ISSUE TITLE
'eloverblik' does not have a valid version key

### ISSUE THREAD

**Issue by hm0hr** [JonasPed/homeassistant-eloverblik#29]
Efter HA update stoppede Eloverblik med at virke, med 'eloverblik' does not have a valid version key. Generelt problem, eller blot min installation? 

EDIT: tilføj: "version": "1.0", til Manifest.json-filen og ting virker igen.

**Comment by JonasPed** [comment]
Version blev tilføjet for ca. 5 måneder siden i nedenstående commit. 

https://github.com/JonasPed/homeassistant-eloverblik/commit/34e309db25410a0e28252d0dfde516fc067f0be3
