### ISSUE TITLE
Feature: Usage with new Energy Dashboard

### ISSUE THREAD

**Issue by henrikbjorn** [JonasPed/homeassistant-eloverblik#30]
The new Energy Dashboard can't find the `total` value. I think this is because the sensor is missing a `last_reset` property.

https://www.home-assistant.io/more-info/statistics/

https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics

Not sure how it works, but it seems that `last_reset` could just be the meeting date.

**Comment by JonasPed** [comment]
For now it is not a feature that I will add as only sensors with present data should support long statistics (see https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics). Eloverblik sensors will always be at least one or two days old. This is not something that can be changed as this is what eloverblik.dk delivers. 

If you insist on using the data you can add a template sensor like below. Just note that data will be shown on the wrong date in statistics card etc. 

template: 
  - sensor: 
    - name: "Eloverblik Long Term Statistics"
      unit_of_measurement: kWh
      state: "{{ states('sensor.eloverblik_energy_total') }}"
      attributes: 
        device_class: energy
        state_class: measurement
        last_reset: "{{ state_attr('sensor.eloverblik_energy_total', 'metering_date') }}"
