### ISSUE TITLE
Eloverblik not showing up in the new "energy" overview

### ISSUE THREAD

**Issue by CarstenHess** [JonasPed/homeassistant-eloverblik#33]
For unknown reasons, the measurements from the Eloverblik integration is not showing up in HA's new "Energy"/"Grid Consumption" settings. 

I'm unsure if this is really an issue with Eloverblik, or if I need to set up some derived entities that converts the measurements into "statistics" or not -- but it would be awesome if it would be added as part of the integration - esp if could retain that "metering date" to ensure that the consumption was shown with the actual date, and not offset.

(and by the way, thanks for implementing this integration in the first place, it's much appreciated!)

**Comment by MikkelFrid** [comment]
Second that! :)

**Comment by MikkelFrid** [comment]
Just perform this step, to make the data long term statistics:
https://github.com/JonasPed/homeassistant-eloverblik#long-term-statistics--energy-dashboard

Then the Energy module will pick up.

Be aware of the two day delay.

**Comment by JonasPed** [comment]
Eloverblik does not belong in the energy dashboard as described here https://github.com/JonasPed/homeassistant-eloverblik#long-term-statistics--energy-dashboard.

**Comment by CarstenHess** [comment]
Ah - sorry that I missed the description 🤦 
But thanks for the explanation.
