### ISSUE TITLE
Consider integration with the new energy management

### ISSUE THREAD

**Issue by KristianOellegaard** [JonasPed/homeassistant-eloverblik#37]
It would be cool if the right attributes could be added so it works with Home Energy Management in the newest version of Home Assistant:

https://www.home-assistant.io/blog/2021/08/04/home-energy-management/

Here is the docs about energy sensors:

https://developers.home-assistant.io/docs/core/entity/sensor

Here is a discussion on what attributes needs to be added:

https://community.home-assistant.io/t/home-energy-management-in-2021-8/325539

Unfortunately, this will also need to address another problem - the fact that the data we receive is from a previous day. I have not yet found a solution for this, it's also being discussed here:

https://community.home-assistant.io/t/energy-counter-delayed-data/332108

**Comment by KristianOellegaard** [comment]
Looks like @allanpersson has solved it already :-) Maybe you would be willing to make a PR @allanpersson?

https://github.com/allanpersson/homeassistant-eloverblik/commit/ad89823b01031309d11e1ba0bd70183715ed3c84#diff-a8d31c8afd06235d0f189875dd436cfb8c865918b6e228a4b4857cd2dda742ed

**Comment by allanpersson** [comment]
> Looks like @allanpersson has solved it already :-) Maybe you would be willing to make a PR @allanpersson?
> 
> https://github.com/allanpersson/homeassistant-eloverblik/commit/ad89823b01031309d11e1ba0bd70183715ed3c84#diff-a8d31c8afd06235d0f189875dd436cfb8c865918b6e228a4b4857cd2dda742ed

Try to look at closed PRs and issues, Jonas has already closed alot of related issues and PR 😇
