### ISSUE TITLE
New HA energy features and long-term statistics​ support

### ISSUE THREAD

**Issue by pbering** [JonasPed/homeassistant-eloverblik#38]
Would be awsome if this integration could expose long-term statistics: https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics, then the "new" energy features should work out of the box: https://www.home-assistant.io/blog/2021/09/01/release-20219/#home-energy-management-updates

**Comment by allanpersson** [comment]
@pbering this issue have been raised multiple times, it won't be included in the integration, please check Readme for reason 🙏

**Comment by pbering** [comment]
Oh sorry, did not spot that :) thanks!
