### ISSUE TITLE
Energy grid consumption

### ISSUE THREAD

**Issue by Langthjem** [JonasPed/homeassistant-eloverblik#40]
It would be awesome to have a sensor for pricing for use in "Grid consumption" as a "Use an entity tracking the total costs". I believe it should be possible to pair the hourly sensors, or a total, with the response from https://api.eloverblik.dk/CustomerApi/api/meteringpoints/meteringpoint/getcharges

**Comment by runemoennike** [comment]
I was also looking at this, but unfortunately it seems it doesn't include the full price:

![image](https://user-images.githubusercontent.com/1521283/150302618-9ac3214b-cabb-4586-bce4-f2bae04be6de.png)

The API documentation [here](https://energinet.dk/-/media/C325FD4EB3AB4AA3BA69AA6BC1049BFD.pdf?la=da&hash=7C1E79635B068097BA44CACC500CEE4A5292DF82) is a bit harder to decipher, but I assume it doesn't have the price from the "elleverandør" either, which means it'd be off by about a third.

**Comment by sorentorp** [comment]
Wouldn't it be easier to add an hour-to-hour table where the user could add those different prices? Maybe it is too different pr. power-supplier?
Fx. https://dinel.dk/priser-og-bestemmelser/#:~:text=Priser%20pr.%201.%20januar%202022

**Comment by runemoennike** [comment]
Your link is to a company that owns the powergrid in an area, and their prices are included in the information from the eloverblik API mentioned above :) The price from the supplier ("el-leverandør") are not included, and indeed they vary widely, also depending on the subscription -- for instance you can get plans where you pay based on the spot price which changes every hour of every day.

**Comment by sorentorp** [comment]
@runemoennike oh, sorry. Is that data presented in Eloverblik in HASS today? I can't seem to find it.

**Comment by runemoennike** [comment]
No it's not presented as of now. This issue is discussing the possibility of adding prices, but that's not possible to do with the data from Eloverblik alone.

**Comment by JonasPed** [comment]
I will see if I can find the time to query the "get charges" endpoint soon and see if the fees and tariffs returned is of any value.

**Comment by runemoennike** [comment]
I was made aware of another plugin that pulls prices from Nordpool, the market where the supplier buys the electricity from: https://github.com/custom-components/nordpool

In theory, it should be possible to combine the data from Nordpool with the data from Eloverblik to calculate the exact kWh price.

**Comment by Langthjem** [comment]
I have successfully achieved the wanted behavior by using the Nordpool integration suggested by @runemoennike.
