### ISSUE TITLE
Would it be possible to add more than 1 token?

### ISSUE THREAD

**Issue by jespersmed** [JonasPed/homeassistant-eloverblik#41]
Hi Jonas,

Very nice work with homeassistant-eloverblik 👍 

I have installed your repository in home assistant and it works awesome. However I also have a summerhouse, would it be possible to somehow enter multiple tokens for more metering points?

br

Jesper

**Comment by JonasPed** [comment]
You should be able to add another instance of the integration and use another token for that one.

**Comment by jespersmed** [comment]
Hej Jones,

Tak for dit svar.

Hvordan mener du at jeg kan tilføje endnu en kopi af den samme integration
og tilføje en ny token?

Jeg er måske lidt rookie i det her, men jeg kan ikke helt se hvordan det
jeg udføre tricket.

mvh

Jesper

Den tir. 11. jan. 2022 kl. 21.45 skrev Jonas Pedersen <
***@***.***>:

**Comment by JonasPed** [comment]
Hvis du går ind under Configuration og så vælger Devices & Services bør du kunne vælge Add Integration of tilføje eloverblik igen.

**Comment by jespersmed** [comment]
Tak

Den tir. 11. jan. 2022 kl. 22.02 skrev Jonas Pedersen <
***@***.***>:
