### ISSUE TITLE
3 sensors that will not disappear

### ISSUE THREAD

**Issue by MicServerKonto** [JonasPed/homeassistant-eloverblik#43]
I have removed eloverblik integration from HA but I still have 3 sensors that will not disappear and everything regarding Eloverblik has been removed from my yaml files and the integration has been removed from HACS.
Is there a solution on how to get rid of the old sensor before I install "electricity overview" again ?

**Comment by JonasPed** [comment]
What are the sensor entities that does not disappear when removing the integration?
