### ISSUE TITLE
eloverblik, are they slow to update data?

### ISSUE THREAD

**Issue by dezral** [JonasPed/homeassistant-eloverblik#44]
I don't see any errors in HA, and the data is 2 days old now..

**Comment by JonasPed** [comment]
If you don't get any errors in the log it is because data is not yet available at eloverblik.dk.

**Comment by woopstar** [comment]
My data is also about 3-4 days behind on eloverblik.dk

**Comment by JonasPed** [comment]
Then there is nothing I can do about it.
