### ISSUE TITLE
Eforsyning not working after 2022.2

### ISSUE THREAD

**Issue by wormiedk** [JonasPed/homeassistant-eloverblik#45]
After upgrading to 2022.2 my e-forsyning stopped working. I get the following in the log:
Logger: homeassistant.setup
Source: setup.py:162
First occurred: 10:01:48 (1 occurrences)
Last logged: 10:01:48

Setup failed for custom integration eforsyning: Requirements for eforsyning not found: ['requests==2.22.0'].

**Comment by wormiedk** [comment]
I also get this
Logger: homeassistant.util.package
Source: util/package.py:99
First occurred: 10:01:44 (3 occurrences)
Last logged: 10:01:48

Unable to install package requests==2.22.0: ERROR: Cannot install requests==2.22.0 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by JonasPed** [comment]
This repository is for the Eloverblik integration and not eForsyning.
