### ISSUE TITLE
[Feature Request] Year-to-date usage

### ISSUE THREAD

**Issue by Inrego** [JonasPed/homeassistant-eloverblik#48]
Would love a sensor that shows the total usage for the current year. It's very useful for people who have heating pumps in their home. After reaching 4000 kWh for a year, the fee on electricity is greatly reduced. Having a sensor to keep track of the total usage for current year, will help keep an eye on when the fees will lower - as well as help in automatically calculating electricity cost at any given moment.

**Comment by Inrego** [comment]
I believe it's as simple as calling the get time series endpoint with the `aggregation` parameter set to `Year` and `dateFrom` set to `{currentYear}-01-01` and `dateTo` set to `{currentYear}-12-31`.

**Comment by runemoennike** [comment]
I agree, would love to see this. Willing to help with a PR.

**Comment by Inrego** [comment]
Would like to see a new version release with this included.

**Comment by runemoennike** [comment]
It should be in 0.3.1 already :)

**Comment by Inrego** [comment]
The commit to add a year to date sensor, was made 27 days ago.
0.3.1 was released 5 months ago?

**Comment by runemoennike** [comment]
You're right, I confused it with another repository.

**Comment by JonasPed** [comment]
Version 0.4.0 just released containing year to date sensor.

**Comment by runemoennike** [comment]
This one can also be closed, I think?

**Comment by Inrego** [comment]
Yes I agree
