### ISSUE TITLE
Access to sensors for outgoing power

### ISSUE THREAD

**Issue by overfrakken** [JonasPed/homeassistant-eloverblik#49]
Can you add sensors showing outgoing power for people with solar panels?
This way you can calculate the net power use/supply per day.

**Comment by JonasPed** [comment]
To my knowledge you can just add the integration again with the "målepunkts id" for your solar panels. I have no way to test it myself as I don't have any solar panels.

**Comment by Coffee0297** [comment]
I tried to add it with the sub id's but the intrgeation just shows unknown data. I think this is bc its a sub id and not a seperate main id.

**Comment by JonasPed** [comment]
> I tried to add it with the sub id's but the intrgeation just shows unknown data. I think this is bc its a sub id and not a seperate main id. also dont use the "nettoforbrug" as its broken ![image](https://user-images.githubusercontent.com/43273303/200138601-02872277-eb1e-4ca5-b980-722396357e77.png)

Is it the sensors that shows unknown? If that is the case what does the log say? Also try to turn on debug logging as described in the readme file.

**Comment by JKNN** [comment]
I have a solar system as well and no easy way to get exported energy from the KOSTAL Inverter integration.

I added the integration and entered the ID for “delivered to grid” meter. Works fine.

However, there is no “total” entity for all years? This is what I need for the default HA Energy Dashboard.

Is this possible to implement @JonasPed ?

**Comment by JonasPed** [comment]
> However, there is no long term “total” entity for all years? This is what I need for the default HA Energy Dashboard.

I don't know if these data is available at all on eloverblik.dk? I don't have any PV panels, so I have no way to test it. 

/Jonas

**Comment by JKNN** [comment]
> I don't know if these data is available at all on eloverblik.dk? I don't have any PV panels, so I have no way to test it.

I think same data is available for both used energy and exported energy. So if all time used energy is available, all time exported energy should be as well.

Looking at your recent commits, I actually think the “total exported energy” will show up with the long term statistics that is yet to be released.

Let me know if you would like access to my meter ID and token for solar energy.

**Comment by JKNN** [comment]
> > I don't know if these data is available at all on eloverblik.dk? I don't have any PV panels, so I have no way to test it.
> 
> I think same data is available for both used energy and exported energy. So if all time used energy is available, all time exported energy should be as well.
> 
> Looking at your recent commits, I actually think the “total exported energy” will show up with the long term statistics that is yet to be released.
> 
> Let me know if you would like access to my meter ID and token for solar energy.

Unfortunately, this does not work. See error from Energy dashboard configuration below. I have set up my “export to grid” meter id in your integration and tries using the long term stats entity without luck.

![5DCE4298-ED03-44D7-AB0F-F0524B37160F](https://user-images.githubusercontent.com/4228900/222928333-15b62b0b-bfaa-415e-851b-eecba4b3dfff.png)
