### ISSUE TITLE
Sensors stay in unknown

### ISSUE THREAD

**Issue by brondum** [JonasPed/homeassistant-eloverblik#5]
Hi.

First of all very nice idea integrating with eloverblik!! 
Have you experienced that sensors stay in unknown ?

**Comment by JonasPed** [comment]
It can happen if data on eloverblik is more than 24 hours delayed. 

Please try with the latest couple of commits. This morning I hopefully fixed an issue if data on eloverblik.dk is more than 24 hours delayed.

**Comment by brondum** [comment]
Cool. Still gets some errors in the logs. but that might be caused by eloverblik it self.
seems to some maintenance today :) 
![image](https://user-images.githubusercontent.com/34370407/77827030-af71a780-7113-11ea-98d1-a474a428d71b.png)

**Comment by rhgiter** [comment]
hi   miss data from time 23-00?

**Comment by JonasPed** [comment]
> hi miss data from time 23-00?

This is unrelated to this issue, but it should be fixed now.

**Comment by brondum** [comment]
Worked like a charm with the initial fix.
Great work!

**Comment by mikaellindemann** [comment]
@JonasPed just installed this through HACS today, provided the token and the MålepunktsID from eloverblik.
In the logs I have the following:

```
2020-04-23 08:52:24 DEBUG (SyncWorker_7) [custom_components.eloverblik] Fetching data from Eloverblik 2020-04-23 08:52:24 WARNING (SyncWorker_7) [custom_components.eloverblik] Exception: <class 'requests.exceptions.HTTPError'> 2020-04-23 08:52:24 DEBUG (SyncWorker_7) [custom_components.eloverblik] Done fetching data from Eloverblik
```

As the exception details are not printed, I'm not sure if it's due to my configuration or data not being available or other issues.
All sensors stays at unknown.
Do you have an idea?
