### ISSUE TITLE
Sensors for pricing data

### ISSUE THREAD

**Issue by runemoennike** [JonasPed/homeassistant-eloverblik#51]
The price of electricity consists of the generation cost, the transport costs, and fees. The generation costs are not available from eloverblik, but can be pulled from Nordpool. However, the transport costs and fees are available from eloverblik, at least on their website, through the "prisdata" export.

Given that this data is also available in their API, it would be very neat to expose it as sensors in this plugin. That way, it can be combined with data from the "Nordpool" plugin to give a pretty accurate hourly price forecast per kWh. The transport costs have to be updated daily, as "peak hour" pricing is different in the summer and winter periods.

@JonasPed unless you have a burning desire to look at this, would you mind if I gave it a shot? I'd also need to add it to your pyeloverblik package. At least I didn't find any code relating to this price data there.

Edit: I've made a PR to pyeloverblik that fetches monthly consumption data, which can be used to implement this one pretty easily.

**Comment by JonasPed** [comment]
Just bumped pyeloverblik to version 0.3.0 that supports reading fees :-)

**Comment by runemoennike** [comment]
Awesome! I can get cracking on this one then.

**Comment by JonasPed** [comment]
I think this one can be closed?

**Comment by runemoennike** [comment]
Yep :)
