### ISSUE TITLE
[Suggestion] Combine into one sensor with more attributes for different hours

### ISSUE THREAD

**Issue by Aephir** [JonasPed/homeassistant-eloverblik#52]
Hi, great work. 

I would like to suggest that all sensors be combined into the `sensor.eloverblik_energy_total` with each `sensor.eloverblik_energy_0_1`, `sensor.eloverblik_energy_1_2`, etc. as attributes in that sensor, kind of like the [Nordpool](https://github.com/custom-components/nordpool) integration for electricity prices (see screenshot).

Mostly just to avoid so many entities in HA. If you need any of those values directly, it's fairly easy to pull them out from attributes. You actually have examples for something like that already.

Nordpool sensor:
![Screenshot 2022-09-10 at 12 58 46](https://user-images.githubusercontent.com/20152788/189480286-b02f8100-9dcc-4362-8182-f1825d4b01a5.png)

**Comment by JonasPed** [comment]
I don't think I will implement this as this break backwards compatibility. Further I don't see any issue in having multiple entities in HA. You don't have to display them all on the dashboard.

**Comment by Aephir** [comment]
I don't show any of them in the dashboard (only used in the background), but they're still in the `States` overview. I do, however, see that the HA devs are trying to limit the amount of data in attributes (as they answered my comment [here](https://community.home-assistant.io/t/wth-are-attributes-such-a-pain-to-work-with/467837/3?u=aephir)), so I think your approach is probably what they'd prefer. 

The main argument (aesthetics of the `states` tab aside) is what I argued in that thread: It's very difficult to work with from the UI - **especially on mobile** - when you have many entities with very similar names (on mobile you can't see the end o the name, so you don't know which of the 24 your are selecting). I'd think that anywhere on the dashboard you'd want to use all these for would probably be a series anyway (e.g. for the [Apexcharts card](https://github.com/RomRider/apexcharts-card)), where it's actually *much* easier to have one entity with the different times in attributes.

<details>

<summary> There it would be as simple as this: </summary>

```
series:
  - entity: sensor.nordpool_kwh_dk2_dkk_3_095_0
    name: Today
    data_generator: |
      return entity.attributes.raw_today.map((entry) => {
        return [new Date(entry.start), entry.value];
      });
    type: column
    show:
      legend_value: false
      in_header: false
  - entity: sensor.nordpool_kwh_dk2_dkk_3_095_0
    name: Tomorrow
    data_generator: |
      return entity.attributes.raw_tomorrow.map((entry) => {
        return [new Date(entry.start), entry.value];
      });
    type: column
    show:
      legend_value: false
      in_header: false
```

</details>

to do this with the 48 hours of prices in the nordpool sensor and the apexcharts card:
<img width="397" alt="Screenshot 2022-10-23 at 22 30 40" src="https://user-images.githubusercontent.com/20152788/197416763-00817d1d-b3f4-458a-8e07-9fc0b12a91b0.png">


That said, it's of course completely up to you, so I'll close and just say thanks for the integration. I'm mainly suggesting based on personal preference of a "cleaner" entity overview (not dashboard) and being able to edit cards on mobile in bed anyway :) And I agree that the backwards compatibility is a good point.
