### ISSUE TITLE
Looks like the integration is broken after the newest HA update

### ISSUE THREAD

**Issue by bjarkeh14** [JonasPed/homeassistant-eloverblik#54]
Looks like the integration is broken after the newest HA update.
None of the entities are showing anything

br
Bjarke

ps
Dansk er helt fint

**Comment by JonasPed** [comment]
Please provide relevant information from the logs. 

Thanks.

**Comment by bjarkeh14** [comment]
Not sure what you need?
This is the log I have from the integration

**This error originated from a custom integration.**

Logger: custom_components.eloverblik
Source: custom_components/eloverblik/__init__.py:107
Integration: Eloverblik
First occurred: 22:05:02 (3 occurrences)
Last logged: 23:19:32

Error from eloverblik: 503 - DataHub unavailable
Error from eloverblik: 500 - {"StatusCode":500,"Message":"An error occurred processing your request"}

**Comment by git4hub1** [comment]
Might be caused from "overload" 

https://eloverblik.dk/customer/login
Showing: Eloverblik er i øjeblikket ikke tilgængelig

and under "Driftinfo" the API overview write about current limitations to calls - guess it's a very popular page at this time :-)

**Comment by JonasPed** [comment]
> Not sure what you need? This is the log I have from the integration
> 
> **This error originated from a custom integration.**
> 
> Logger: custom_components.eloverblik Source: custom_components/eloverblik/**init**.py:107 Integration: Eloverblik First occurred: 22:05:02 (3 occurrences) Last logged: 23:19:32
> 
> Error from eloverblik: 503 - DataHub unavailable Error from eloverblik: 500 - {"StatusCode":500,"Message":"An error occurred processing your request"}

It basically just says that eloverblik is unavailable at the moment due to "internal server error" or "service unavailable". This is not related to HA or this integration.
