### ISSUE TITLE
Support for more "Measurepoints" - with proper naming

### ISSUE THREAD

**Issue by askpet** [JonasPed/homeassistant-eloverblik#58]
Feature request

I have heatpump as central heating system, and thus low tax on kWh above 4000 kWh.
Due to that fact - I have two measurepoints in Eloverblik.dk. One that represents my main measurepoint and one (with an id 10 points lower than my main measurepount. It represents the daily added 4000/365 kWh of which I have to pay full taxation. The sensor "tariff_sum" from my main measurepoint only have the low taxation (0,008 kr excluding wat). It would be nice having the other as well.
It is possible to invoke two integrations - but the naming - including the friendly names are the same - which result in an annoying "_2" at the end of all the names.
So - I know its possible - but not easy to recognize at all.

**Comment by JonasPed** [comment]
Just to understand your request correctly. You would like the tariffs from the second measurement point to be included in the first one? This is to avoid setting up the integration twice with two different metering points.
