### ISSUE TITLE
Eloverblik Monthly Statistics - Broken i version 2022.12.0

### ISSUE THREAD

**Issue by msj33** [JonasPed/homeassistant-eloverblik#65]
Nedenstående config fra dokumentationen virker ikke længere:

Får følgende fejl i loggen:
Invalid config for [sensor.statistics]: required key not provided @ data['state_characteristic']. Got None. (See /config/configuration.yaml, line 37). Please check the docs at https://www.home-assistant.io/integrations/statistics

sensor:
  - platform: statistics
    entity_id: sensor.eloverblik_energy_total
    name: Eloverblik Monthly Statistics
    sampling_size: 50
    max_age:
        days: 30

**Comment by Blaatanden** [comment]
Jeg fik en besked på at jeg før opdatering til 2022.12.0 skulle tilføje en linje til sensoren:

sensor:
  - platform: statistics
    entity_id: sensor.eloverblik_energy_total
    name: Eloverblik Monthly Statistics
    state_characteristic: mean
    sampling_size: 50
    max_age:
        days: 30

**Comment by JonasPed** [comment]
Dokumentationen er blevet opdateret.
