### ISSUE TITLE
Kan ikke installere

### ISSUE THREAD

**Issue by scaglar78** [JonasPed/homeassistant-eloverblik#67]
Jeg kører HA december 2022 versionen og kan ikke installere eloverblik via HACS.
Jeg downloader fint og genstarter HA herefter som anvist, men der dukker ikke noget op i forhold til start eller konfiguration af eloverblik add-on... Nogen der oplever det samme eller har en løsning til mit problem?

**Comment by JonasPed** [comment]
Jeg har netop prøvet at installere integrationen via HACS på en hel frisk HA installation. Der oplever jeg ingen problemer.
