### ISSUE TITLE
Updates only when restarting Home Assistant

### ISSUE THREAD

**Issue by rosenbaek** [JonasPed/homeassistant-eloverblik#7]
Hi,

Just realized data was only updated when I restarted Home Assistant. Before I did the restart of HA I checked eloverblik.dk (my last data in HA was from the 28th Mar.) and there was data on the eloverblik.dk from the 29 and 30th March but not from yesterday the 31th. I did a restart and the the integration updated to the 30th with correct attribute "Metering date: '2020-03-30'"(this is a huge improvement). 

Before I did a restart I tried to update the entity via the service homeassistant.update_entity, but nothing happened. But seem like the restart triggered an update process. 

Keep op the great work! Thanks.

**Comment by JonasPed** [comment]
Hi
I also noticed this today. Currently I have no idea why it happens. I am trying to debug this a bit. It does however take a bit of time as data is only updated once a day at eloverblik.dk.
