### ISSUE TITLE
Integration uses January tariffs even though we are now in February

### ISSUE THREAD

**Issue by KennethLavrsen** [JonasPed/homeassistant-eloverblik#72]
It is the 1st of February. I am in Denmark DK2

The tariff sum is still showing the January value. I tried to both restart HA and reload the integration, but the value remains January value. So either the integration does not update or the data source is not reliable.

**Comment by JonasPed** [comment]
Basically the integration is just showing what received from eloverblik. Can you please try to add debug logging as described in the README.md file?

**Comment by drlauridsen** [comment]
Was about to report almost same issue.
Tariffs do not reflect the correct amount (at least for Radius), and it it not related to VAT - the reported tariffs are lower than the stated tariffs (with VAT) on Radius website for højlast and spidslast, but higher for lavlast.

Downloading current data from eloverblik (excel data) - the tariffs are correct  (without VAT), so something is wrong with the data coming from the API?

**Comment by drlauridsen** [comment]
![Screenshot_20230208_003954_Excel](https://user-images.githubusercontent.com/61352332/217391991-29d3bc46-c38e-4840-9829-00270de6e5db.jpg)
![Screenshot_20230208_001349_Home Assistant](https://user-images.githubusercontent.com/61352332/217391994-fad55d3f-589c-46b3-b8d9-19c2793100d4.jpg)

**Comment by KennethLavrsen** [comment]
Ping

**Comment by drlauridsen** [comment]
Still an issue... the tariffs are not correct

**Comment by JonasPed** [comment]
Please provide the debug logging as requested.

**Comment by KennethLavrsen** [comment]
Jonas

the issue I reported relates to the change from the last day of the month to the first day of next month where the tariffs are not updated. I was travelling on business on March 1st and on vacation also travelling on April 1st. And on May 1st the tarifs did not change and next update will be in July when taxes increase again and then next time is 1st of October when the next winter tarifs are announced to start. I was hoping the other participants had the chance to capture logs on the night of the 1st. Logs from mid months will show that all is ok and will not help anyone

**Comment by KennethLavrsen** [comment]
and anyone getting notifications, do not try making logs tonight as Eloverblik is down all night the 10th of May until 23:00

**Comment by KennethLavrsen** [comment]
Pinging bot

**Comment by runemoennike** [comment]
The tariffs are correct for me, so I assume this only happens the day after they change, or what?

**Comment by KennethLavrsen** [comment]
Forgot to check. Waiting for next change

**Comment by KennethLavrsen** [comment]
Those tarifs change next time april 1st
