### ISSUE TITLE
Blande realtime og Eloverblik historiske data

### ISSUE THREAD

**Issue by oschmitto** [JonasPed/homeassistant-eloverblik#74]
Hejsa,
Jeg modtager ind i Home Assistant Energy dashboard realtime data fra min egen kamstrup måler, hvori der er monteret en læser som sender data hvert 10 sek. 

Jeg har haft denne løsning siden juli 2022, så jeg mangler lige nu historiske data fra januar til og med maj 2022 

Jeg forstår at jeg også kan hente historiske data fra Eloverblik via denne integration.

Så vil den kunne finde ud af at jeg har allerede nogle historiske data inde i Home Assistant, men at den skal hente eksempelvis de historiske data fra januar 2022 fra Eloverblik?

**Comment by JonasPed** [comment]
Nej. Det vil være to forskellige sensorer i HA og de kender som sådan ikke til hinanden.
