### ISSUE TITLE
Feature request: Get CO2 data

### ISSUE THREAD

**Issue by JKNN** [JonasPed/homeassistant-eloverblik#76]
You can now see your CO2 emission in eloverblik ref my picture. Would be great if we can have this in HA as well.

![1CB8AB1B-B9C9-4558-B9B3-0B846E391606](https://user-images.githubusercontent.com/4228900/221111272-20a315f7-f069-4737-aa18-8799fec8e2d9.jpeg)

**Comment by JonasPed** [comment]
As far as I can see these data is not exposed through the API, so I will not be able to expose it to HA.

**Comment by MariusVB** [comment]
Actually the data is exposed. I'll explain what the website does and we could look into implementing it. 

1. Get the hourly consumption of a meter. The website takes it one year at a time. Example URL for 2022: https://api.eloverblik.dk/CustomerApi/api/MeterData/GetTimeSeries/2022-01-01/2023-01-01/Hour
2. Get emission data for the corresponding year. Example URL for 2022: https://din-deklaration.eloprindelse.dk/data/2022_emission_data.json
3. Use the logic in the script at https://din-deklaration.eloprindelse.dk/script.js to generate the report.

The js script exposes most of the logic and it shouldn't be to hard to port to python. It is basically just a CO2 value pr. hour multiplied by your hourly kWh usage, with some added complexity if we want stats pr. individual power source.
