### ISSUE TITLE
Error from eloverblik when getting meter rading data: 404 - No readings found in result.

### ISSUE THREAD

**Issue by DurgNomis-drol** [JonasPed/homeassistant-eloverblik#79]
Får denne fejl meddelelse:
```Error from eloverblik when getting meter rading data: 404 - No readings found in result.```

Men integration virker til at hente alt det den skal 😃

**Comment by edtwodth** [comment]
Har samme problem

**Comment by DurgNomis-drol** [comment]
For mig stopper integration med at importere statistisk data, men den opdatere stadigvæk alt det andet

**Comment by JonasPed** [comment]
> For mig stopper integration med at importere statistisk data, men den opdatere stadigvæk alt det andet

Jeg tror ikke det er på grund af denne besked men på grund af det andet issue du har rapporteret.
