### ISSUE TITLE
Suggested presentation in Home Assistant

### ISSUE THREAD

**Issue by martinrosenauer** [JonasPed/homeassistant-eloverblik#8]
Hi Jonas,

First of all, thanks for providing us with this plugin. Got it well installed and see sensors in HASS - wondering if there is some suggested, cool way of presenting them in HASS and get history, barcharts, or similar. What have you done yourself?

Thanks!

**Comment by JonasPed** [comment]
Currently I am only using the daily sensor. I plan on create some visualization that shows the trend of my power usage.

**Comment by martinrosenauer** [comment]
Ok - I ended up recording to MariaDB, and are using Grafana for barcharts of daily totals. Presenting those inside Home Assistant works well ..

**Comment by knoer** [comment]
Hi all,

I'd like to chime in on this one - mostly to say I really like the possibilities of using this HA plugin. 
Awesome work so far @JonasPed !

I have only gotten so far as to install this on my test-HA, and sort of stalled when trying to create a meaningful card with all the available sensors in HA - so if it is possible to supply a "standard" card with the plugin - perhaps a bargraph/linechart or such over the past months daily total or so - that would be awesome.

Also, I think, a very interesting possible use of this plugin is to visualize changes in a household's total stand-by/idle energy consumption - for instance, monitoring/averaging the consumption in the period between 02:00 and 05:00 will, in my case, show the "unavoidable" consumption from refrigerator/freezer/IT equipment/ventilation - and the possibly avoidable consumption from equipment on stand-by, chargers etc. sitting around the house.

This could also be used as an indicator on how much energy that new A+++ freezer actually saves - or how much more/less the new server will cost over the course of a year ;-)

**Comment by ZenithDK** [comment]
> 
> 
> Ok - I ended up recording to MariaDB, and are using Grafana for barcharts of daily totals. Presenting those inside Home Assistant works well ..

Sounds awesome - care to share in a gist or somewhere others can nick them?

**Comment by blidegn** [comment]
Hi all,

I am recording to InfluxDB and using InfluxDB(Dashboard) and Grafana for visualization.
Got started with InfluxDB and Grafana by watching this video:
https://www.youtube.com/watch?v=m9qIqq104as

**Comment by JonasPed** [comment]
For visualization @blidegn 's solution with Grafana and InfluxDB is the right solution in my opinion. This is also what I am using. 

I can imagine so many different ways that people want to visualize the data that it will be more or less impossible to maintain specific sensors for each requirement. I believe people should create template sensors, use Grafana/InfluxDB etc. for their needs. If someone have some cool solutions they are more than welcome to send PR's that update the README.md with examples or maybe create an examples folder.

**Comment by Nordicfastware** [comment]
HI, I am unable to install Hass IO on my Qnap NAS, so I am currently stuck with vanilla Home Assistant. So the installation of Grafana and Influx DB is significantly more complex(though feasible. So I have resorted to make a mix or templates, utility meters with many tweaks to avoid double counting due to relative randomness of data retrieval. It is also shown with the wrong time stamp. Far from perfect, but once you know what you are looking at, it give the trend... And when I want details I just download the excel export and make data model (power query) and pivot charts (low tech).

So yeah, it would be great to have a standard way to display this properly. That can be achieved by sharing some methods between ourselves, and also potentially adapting how the sensors are created/process in the integration.

**Comment by HBDK** [comment]
Hi,
i so i wanted to make a graph i could show in my frontend but i couldn't see any good way to do it in home assistant, so instead i made a small add on that takes the hourly sensors and put the values into my influx db as a time series i can plot.

![](https://i.imgur.com/dlcnwWn.png)


i have a automation in home assistant that starts this add on every time the meter date changes.

i have published the add-on [here](https://github.com/HBDK/ElOverBlik-helper) if some of you would like to give it a go. 
it is structured as a repository so you can just add the url to home-assistant.

**Comment by JonasPed** [comment]
I have updated the README.md file with an example of how to visualize it in Home Assistant.

Closing this issue. Other examples are welcome as PR's.
