### ISSUE TITLE
Opdatere ikke statistics efter jeg har sat integration op

### ISSUE THREAD

**Issue by DurgNomis-drol** [JonasPed/homeassistant-eloverblik#83]
Som titlen siger, så opdatere den ikke statistics data efter jeg har sat den op. Den henter alle de andre data, men den indsætter dem ikke. Når jeg går ind på eloverblik.dk så kan jeg se data at der er data, men den henter det ikke/indsætter det ikke som statistics i databasen, for jeg kan ikke se det i mit energi panel.

Sig frem hvis du har brug for mere information, lige nu er jeg på bar bund omkring hvorfor. Jeg kan evt. indsætte nogle log statements i integration hvis det kan hjælpe?

**Comment by OEHC** [comment]
Jeg tror at PR #82 vil fikse det. Den fikser en fejl i `_update_data()` som netop indsætter long term stats kontinuert.

**Comment by DurgNomis-drol** [comment]
@OEHC Dit PR fikser problemet så vidt jeg kan se 😃

**Comment by OEHC** [comment]
@DurgNomis-drol Off topic men af nysgerrighed; hvordan har du testet det? Jeg ville også gerne have testet det, men ved ikke hvordan jeg skal bære mig ad med at ændre versionen af et HACS plugin uden en release.

**Comment by DurgNomis-drol** [comment]
Ændrede bare filerne lokalt, så kunne jeg se at den nu automatiks opdatere.

**Comment by JonasPed** [comment]
Should be fixed in latest release.
