### ISSUE TITLE
Data 2 dage bagud?

### ISSUE THREAD

**Issue by edtwodth** [JonasPed/homeassistant-eloverblik#85]
Hej, skal bare lige sikre mig, at jeg ikke har misforstået noget.

Jeg har lavet oversigt med elforbrug de sidste 7 dage, men den er altid 2 dage bagefter? Den viser 7 dage, men der er kun tal i de 5 af dagene? F.eks. er der i dag kun data indtil den 11? 

![Skærmbillede 2023-03-14 kl  11 17 18](https://user-images.githubusercontent.com/54725502/224969657-8486b66b-4577-4f44-a515-723d22bed999.png)

**Comment by JonasPed** [comment]
Integrationen viser blot de data der er tilgængelige på eloverblik.dk. Så hvis eloverblik.dk ikke visere nyere data kan integrationen heller ikke.

**Comment by anes300** [comment]
Oplever samme problem her, på trods af at dataen er tilgængelig i eloverblik.dk.

**Comment by JonasPed** [comment]
> Oplever samme problem her, på trods af at dataen er tilgængelig i eloverblik.dk.

Prøv at slå debug logging til når du oplever problemet og vedhæft output fra loggen. Der står beskrevet i README.md filen hvordan man gør.
