### ISSUE TITLE
Problemer med opdatering af data

### ISSUE THREAD

**Issue by bossybum** [JonasPed/homeassistant-eloverblik#87]
Hej med jer,

Jeg oplever at integrationen ikke opdaterer data, men hvis jeg laver den igen - får jeg opdaterede data.
Jeg kører version V.0.5.2 og den tidligere sensor.py fix - er ikke relevant, da den manglende "bracket" er i min python fil.
Dog skal det siges, at jeg har to "MålepunktsID" sat op, hvor samme token benyttes. What to do ?

**Comment by tristangrichard** [comment]
Samme her dog kun med et `MålepunktsID`.
Har prøvet at reload integrationen, men nu er alt data væk.

**Comment by JonasPed** [comment]
Står der noget i loggen?

Slå også gerne debug logging til og vedhæft output fra log når problemet er opstået.

**Comment by tristangrichard** [comment]
@JonasPed Jeg tager det i mig igen.
Tror bare det er DSO der er langsom
