### ISSUE TITLE
Data is 2 days old

### ISSUE THREAD

**Issue by briis** [JonasPed/homeassistant-eloverblik#9]
Hi Jonas,
Thanks for making this. I just installed it, and notice that data is from April 18th, so 2 days old. Is this supposed to be like that? I can download data from the website for today.

**Comment by JonasPed** [comment]
The integration is showing the newest data that is delivered by the eloverblik.dk API. How fast eloverblik.dk is updated varies a lot. I have seen other cases where data is 2 days old as well. I have also seen cases where data is updated a few hours after midnight.

**Comment by briis** [comment]
Thanks Jonas. We have to live what eloverblik is delivering.
