### ISSUE TITLE
Hvilket Målepunkt ID skal tilknyttes ?

### ISSUE THREAD

**Issue by Snotskovl01** [JonasPed/homeassistant-eloverblik#91]
Beklager at forstyrre med denne lille ting, men jeg kan ikke få data frem i integrationen - al opsætning gik smertefri og jeg får dialogboxen med token og målepunkts id. Har forsøgt at tilknytte alle de målepunkts id´er jeg kan finde, men data er tom og når jeg trykker genindlæser, så får jeg en fejl. 
Hvad er det jeg misser ?

**Comment by JonasPed** [comment]
Desværre er Eloverblik.dk API kendt for at være ret ustabil og langsom og det kan jeg, desværre, ikke gøre noget ved. 

Står der noget i loggen?
