### ISSUE TITLE
Data for sensor.eloverblik_energy_statistic er forskudt med en dag.

### ISSUE THREAD

**Issue by StaticSounds90** [JonasPed/homeassistant-eloverblik#97]
Data i sensor.eloverblik_energy_statistic er forskudt med en dag.

Udklip af data manuelt hentet fra eloverblik.dk og repræsentation af sensordata i HA
![image](https://github.com/JonasPed/homeassistant-eloverblik/assets/154476033/9a8b2e69-ea31-4b34-be25-a09dee0b7b9c)
![image](https://github.com/JonasPed/homeassistant-eloverblik/assets/154476033/6e99edcd-0bd2-47eb-a9c0-675ca4c1a39a)

**Comment by JonasPed** [comment]
What is the YAML behind the graph?

**Comment by StaticSounds90** [comment]
![image](https://github.com/JonasPed/homeassistant-eloverblik/assets/154476033/f21f3e40-c1e4-4629-8327-b4f91376254d)

**Comment by JonasPed** [comment]
I just checked my statistics sensor in the energy dashboard and that shows correctly. The sensor is only inteded to be used in the energy dashboard. 

I am no apex charts expert, but could it be due to the fact that you have offset: -1d?

**Comment by StaticSounds90** [comment]
It would seem apexcharts skipped the 31 of March and the issue is with apexcharts - maybe leap year issue. 
I confirmed this by using the Statistic card.

![image](https://github.com/JonasPed/homeassistant-eloverblik/assets/154476033/1be0b162-631f-4b0b-8667-0a53ec18d84e)
![image](https://github.com/JonasPed/homeassistant-eloverblik/assets/154476033/eb514d4a-0ab8-4978-bd1b-60294b54d011)
![image](https://github.com/JonasPed/homeassistant-eloverblik/assets/154476033/04109475-a471-4f14-b733-a8df3456e7db)
![image](https://github.com/JonasPed/homeassistant-eloverblik/assets/154476033/aae6e0e6-14a8-403c-9e57-c9515910f048)
