### ISSUE TITLE
Can't load statistic sensors

### ISSUE THREAD

**Issue by gianmarcomurru** [JonasPed/homeassistant-eloverblik#98]
Hello! Since I have installed this plugin I could retrieve all the sensors but these ones. I really like this integration and it should do exactly what I need but without these statistics sensor I can't integrate this with my Energy HA integration which is too bad 😞

<img width="1251" alt="Screenshot 2024-03-31 at 14 59 25" src="https://github.com/JonasPed/homeassistant-eloverblik/assets/48201852/c3541833-2dad-427b-8e29-178c0decfc7a">

Do you know what it could be the issue? (I have installed it from HACS)
Thank you in advance!

**Comment by JonasPed** [comment]
This is working as intended. Please see https://github.com/JonasPed/homeassistant-eloverblik?tab=readme-ov-file#long-term-statistics-and-energy-dashboard.

**Comment by gianmarcomurru** [comment]
I see, my bad! I am still not quite sure hoe to integrate it into the Energy dashboard. Do I have to create a long-term entity my self or is automatically created?

Thanks again for your answer!

**Comment by JonasPed** [comment]
You just have to add the sensor to the energy dashboard and it will get updated back in time.

**Comment by Fywqdk** [comment]
Hi Jonas,

I have tried adding in the statistic card with yesterdays consumption but I just get a ? I can get the values on the bar chart for the past week or month from the other example, so I am pretty sure my token/key is working correctly. I can also get a value on this card if I set the offset to -2 or a higher negative number. Any idea what may be wrong? Is it just that they don't update the value on a day-to-day basis?

**Comment by JonasPed** [comment]
> Hi Jonas,
> 
> I have tried adding in the statistic card with yesterdays consumption but I just get a ? I can get the values on the bar chart for the past week or month from the other example, so I am pretty sure my token/key is working correctly. I can also get a value on this card if I set the offset to -2 or a higher negative number. Any idea what may be wrong? Is it just that they don't update the value on a day-to-day basis?

Sounds like data is not yet available in Eloverblik.

**Comment by Fywqdk** [comment]
Yeah seems like they are just too slow at updating data for my liking. Now to look into custom ways to get data from my kamstrup non-smart meter...
